name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: |
          TIMESTAMP=$(date +%s)
          docker build . --file Dockerfile --tag my-image-name:$TIMESTAMP

      - name: Run the Docker container
        run: |
          TIMESTAMP=$(date +%s)
          docker run -d -p 8787:8787 -e PASSWORD=yourpassword my-image-name:$TIMESTAMP

      - name: Verify the Docker container is running
        run: docker ps -a

      - name: Clean up
        run: |
          docker stop $(docker ps -q --filter ancestor=my-image-name:$TIMESTAMP)
          docker rm $(docker ps -a -q --filter ancestor=my-image-name:$TIMESTAMP)
